export const GOAL = {
  MIN_DAILY_CALORIES: 1000,
  MAX_DAILY_CALORIES: 10000,
  DEFAULT_DAILY_CALORIES: 2000,
} as const;

export const PROGRESS_BAR = {
  WIDTH: 800,
  HEIGHT: 280,
  BACKGROUND_COLOR: "#FFFFFF",
  BAR_BACKGROUND_COLOR: "#E5E7EB",
  BAR_FILL_COLOR: "#3B82F6",
  TEXT_COLOR: "#1F2937",
  TITLE_FONT_SIZE: 32,
  VALUE_FONT_SIZE: 48,
  PERCENTAGE_FONT_SIZE: 36,
  LABEL_FONT_SIZE: 24,
  PADDING: 40,
  BAR_HEIGHT: 60,
  BAR_BORDER_RADIUS: 30,
} as const;

