export const ONBOARDING = {
  MESSAGES: {
    WELCOME: `Olá! Seja muito bem-vindo ao Meals AI! 😊\n\nEu sou seu assistente nutricional pessoal e estou aqui para te ajudar a acompanhar sua alimentação de forma simples e prática.\n\nAntes de começarmos, preciso saber: qual é a sua meta diária de calorias? 🔥\n\nPor favor, me informe um número (exemplo: 2000, 2500, etc.)`,
    EXPLAINING: `Perfeito! Deixa eu te explicar como funciona: 📚\n\nA funcionalidade principal do Meals AI é a análise nutricional das suas refeições. Você pode fazer isso de duas formas:\n\n1️⃣ **Por texto**: Descreva sua refeição\n   Exemplo: "2 peitos de frango grelhado, 200g de arroz e salada"\n\n2️⃣ **Por foto**: Envie uma foto do seu prato\n   Eu analiso a imagem e identifico os alimentos\n\nQuando você envia uma refeição, eu:\n• Identifico os alimentos\n• Calculo os valores nutricionais (calorias, proteínas, carboidratos, lipídios)\n• Salvo automaticamente para você acompanhar seu progresso\n• Mostro seu progresso em relação à sua meta diária de calorias\n\nAgora vamos praticar! 🎯\n\nEnvie uma descrição de uma refeição para eu analisar. Pode ser algo simples como:\n"1 peito de frango e 150g de arroz"`,
    PRACTICING_SUCCESS: `Parabéns! Você conseguiu! 🎉\n\nVocê acabou de usar a funcionalidade principal do Meals AI! Agora você já sabe como:\n• Enviar refeições para análise\n• Receber informações nutricionais detalhadas\n• Acompanhar seu progresso em relação à sua meta\n\nOutras funcionalidades que você pode usar:\n• Digite "resumo" ou "hoje" para ver seu resumo do dia\n• Digite "relatório semanal" ou "semana" para ver relatórios completos\n• Digite "ajuda" a qualquer momento para ver os comandos\n\nEstou sempre aqui para te ajudar! Boa sorte na sua jornada nutricional! 💪🌟`,
    PRACTICING_RETRY: `Não consegui identificar uma refeição na sua mensagem. 😅\n\nTente descrever algo como:\n• "1 peito de frango e 150g de arroz"\n• "2 ovos, pão e café"\n• "salada com frango grelhado"\n\nOu envie uma foto do seu prato! 📸\n\nVamos tentar novamente?`,
    GOAL_INVALID: `Desculpe, não consegui entender sua meta de calorias. 😅\n\nPor favor, me informe um número válido entre 1000 e 10000 calorias.\n\nExemplos:\n• 2000\n• 2500\n• 1800`,
  },
} as const;

